---
title: "Homework 8"
date: "Due: 11:59pm, Wednesday, April 15"
output: 
  html_document: 
    css: hw.css
    theme: yeti
    toc: true
    fig_caption: false
    toc_float:
      collapsed: false
      smooth_scroll: true
---

## Instructions

Please make sure your final output file is a pdf document. You can submit handwritten solutions for non-programming exercises or type them using R Markdown, LaTeX or any other word processor. All programming exercises MUST be done in R, typed up clearly and with all code attached. Submissions should be made on gradescope: go to Assignments $\rightarrow$ Homework 8.

## Questions

1. <font color="blue">**Biased coin problem.**</font> Suppose we have univariate data $y_1, \ldots, y_n | \theta \sim \text{Bernoulli}(\theta)$ and wish to test: $\mathcal{H}_0: \theta = 0.5 \ \ \text{vs. } \mathcal{H}_1: \theta \neq 0.5$.
    + <font color="green">**Part (a):**</font> Formulate this hypothesis testing problem in a Bayesian way. Specify all the necessary steps and come up with your own priors where necessary.
    + <font color="green">**Part (b):**</font> Derive and simplify the marginal likelihoods $\mathcal{L}[Y | \mathcal{H}_0]$ and $\mathcal{L}[Y | \mathcal{H}_1]$.  
    <font color="red">*For each marginal likelihood, you'll need to start with the joint posterior between hypothesis and model parameter, and integrate out the parameter. For example, $\mathcal{L}[Y | \mathcal{H}_0] = \int_{\Theta} p(Y, \theta | \mathcal{H}_0) \text{d}\theta =  \int_{\Theta} \mathcal{L}[Y | \mathcal{H}_0, \theta] \cdot \pi(\theta | \mathcal{H}_0) \text{d}\theta$, where $\mathcal{L}[Y | \mathcal{H}_0, \theta]$ is the likelihood for the data under the null hypothesis and $\pi(\theta | \mathcal{H}_0)$ is your prior under the null hypothesis. Keep all normalizing factors when integrating.* </font>
    + <font color="green">**Part (c):**</font> Derive the Bayes factor in favor of $\mathcal{H}_1$. Also, derive the posterior probability of $\mathcal{H}_1$ being true. Simplify both as much as possible.
    + <font color="green">**Part (d):**</font> Study the asymptotic behavior of the Bayes factor in favor of $\mathcal{H}_1$. For $\theta \in \{0.25, 0.46, 0.5, 0.54\}$, make a plot of the Bayes factor (y-axis) against sample size (x-axis). You should have four plots. Comment on the implications of the true value of $\theta$ on the behavior of the Bayes factor in favor of $\mathcal{H}_1$, as a function of sample size. When answering this question, remind yourself of what Bayes factors actually mean and represent!


2. <font color="blue">**Metropolis-Hastings.**</font> Consider the following sampling model: $$y_1, \ldots, y_n | \theta_1, \theta_2 \sim p(y | \theta_1, \theta_2),$$
with the priors on $\theta_1$ and $\theta_2$ set as $\pi_1(\theta_1)$ and $\pi_2(\theta_2)$ respectively, where $\theta_1, \theta_2 \in \mathbb{R}$.

    Suppose we are interested in generating random samples from the posterior distribution $\pi(\theta_1, \theta_2 | y_1, \ldots, y_n)$. For each of the following proposal distributions, write down the acceptance ratio for using Metropolis-Hastings to generate the samples we desire. Make sure to simplify the ratios as much as possible for each proposal!
    + <font color="green">**Part (a):**</font> Full conditionals: 
    $$
    \begin{split}
    g_{\theta_1}[\theta_1^\star | \theta_1^{(s)}, \theta_2^{(s)}] & = p(\theta_1^\star | y_1, \ldots, y_n, \theta_2^{(s)});\\
    g_{\theta_2}[\theta_2^\star | \theta_1^{(s)}, \theta_2^{(s)}] & = p(\theta_2^\star | y_1, \ldots, y_n, \theta_1^{(s)}).
    \end{split}
    $$
    + <font color="green">**Part (b):**</font> Priors:
    $$
    \begin{split}
    g_{\theta_1}[\theta_1^\star | \theta_1^{(s)}, \theta_2^{(s)}] & = \pi_1(\theta_1^\star);\\
    g_{\theta_2}[\theta_2^\star | \theta_1^{(s)}, \theta_2^{(s)}] & = \pi_2(\theta_2^\star).
    \end{split}
    $$
    + <font color="green">**Part (c):**</font> Random walk:
    $$
    \begin{split}
    g_{\theta_1}[\theta_1^\star | \theta_1^{(s)}, \theta_2^{(s)}] & = \mathcal{N}(\theta_1^{(s)}, \delta^2);\\
    g_{\theta_2}[\theta_2^\star | \theta_1^{(s)}, \theta_2^{(s)}] & = \mathcal{N}(\theta_2^{(s)}, \delta^2).
    \end{split}
    $$
    
    <font color="red">*In each case, you only need to spend time working through the acceptance ratio for one of the two parameters. The other one should become obvious once you've completed the first.* </font>
    
  
## Grading

20 points.
  