---
title: "Homework 1"
date: "Due: 11:59pm, Monday, July 6"
output: 
  html_document: 
    css: hw.css
    theme: yeti
    toc: true
    fig_caption: false
    toc_float:
      collapsed: false
      smooth_scroll: true
---

## Instructions

This assignment involves some probability review and one parameter models. Please make sure your final output file is a pdf document. You can submit handwritten solutions for non-programming exercises or type them using R Markdown, LaTeX or any other word processor. All programming exercises must be done in R, typed up clearly and with all code attached. Submissions should be made on gradescope: go to Assignments $\rightarrow$ Homework 1 (360) for students in STA 360 and Homework 1 (602) for students in STA 602.

## Questions

1. There are three coins in a bag; two fair coins (probability of heads = probability of tails) and one fake coin (probability of heads = 1). 
    + <font color="green">**Part (a):**</font> You reach in and select one coin at random and throw it in the air. What is the probability that it lands on heads?  
    <font color="blue">**(1 point for all students)**</font>
    + <font color="green">**Part (b):**</font> You reach in and select one coin at random and throw it in the air and get heads. What is the probability that it is the fake coin?  
    <font color="blue">**(Students in STA 360: 2 points; Students in STA 602: 1.5 points)**</font>
    
2. Hoff 2.3
    + <font color="blue">**Part (a): 2 points for all students**</font>
    + <font color="blue">**Part (b): 2 points for all students**</font>
    + <font color="blue">**Part (c): 1 point for all students**</font>

3. Show that the posterior variance of the beta-binomial model can be written as
$$\mathbb{V}(\theta | y) = \dfrac{\mathbb{E}(\theta | y)\mathbb{E}(1-\theta | y)}{a+b+n+1}.$$  
<font color="blue">**(2.5 points for all students)**</font>

    
4. Hoff 3.1. 
    + <font color="blue">**Part (a): 0.5 points for all students**</font>
    + <font color="blue">**Part (b): Students in STA 360: 2 points; Students in STA 602: 1 point**</font>
    + <font color="blue">**Part (c): Students in STA 360: 2 points; Students in STA 602: 1 point**</font>
    + <font color="blue">**Part (d): Students in STA 360: 2 points; Students in STA 602: 1.5 points**</font>
    + <font color="blue">**Part (e): 2 points for all students**</font>

    <font color="red">*Don't work out part (a), just say what the correct sampling distribution is (you should already know) and move on to the remaining parts.*</font>

5. Using the inverse cdf method, generate 1,000 random realizations from the Beta(5,10) distribution truncated to the interval (0.4,0.75).
    + <font color="green">**Part (a):**</font>  What is the mean of your random draws (rounded to 2 decimal places)?  
    <font color="blue">**(0.5 points for all students)**</font>
    + <font color="green">**Part (b):**</font>  What is the variance of your random draws (rounded to 2 decimal places)?  
    <font color="blue">**(0.5 points for all students)**</font>

6. <font color="green">Continuation of the "new agent" example from class</font>. For each of the priors (that is, <font color="red">Beta(1,666)</font>, <font color="red">Beta(0.05,33.33)</font>, <font color="red">Beta(1.6, 407.4)</font>, <font color="red">Beta(1.05, 497)</font>, and <font color="red">Unif(0,0.1)</font>), how many trials would we need, assuming no adverse reactions, to be 95% sure that the new agent is as safe as (or safer than) the old one? That is, what value of $n$ is required to ensure that $\Pr(\theta_N \leq 0.0015| y) = 0.95$?  
<font color="blue">**(Students in STA 360: Skip; Students in STA 602: 3 points)**</font>

    <font color="red">*You don't need to do any rigorous math here. Do it in R!*</font>


7. Hoff 3.2.  
<font color="blue">**(Not graded. Attempt for practice but you don't need to submit!)**</font>

    <font color="red">*Refer back to pages 5 to 7 of the Hoff book (the section on sensitivity analysis) if you are not sure what to do.*</font>


## Grading

Total: 20 points.
  