---
title: "Hierarchical models II; introduction to regression models"
output: 
  html_document:
    css: reading.css
    theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Required:

- [A First Course in Bayesian Statistical Methods](https://www.amazon.com/Bayesian-Statistical-Methods-Springer-Statistics/dp/0387922997) by Peter D. Hoff.:
    + Section 8.4: Example: Math scores in U.S. public schools
    + Section 8.5: Hierarchical modeling of means and variances
    + Section 8.6: Discussion and further references
    + Section 9.1: The linear regression model
    + Section 9.2: Bayesian estimation for a regression model
    

## Optional:

- [Bayesian Data Analysis (Third Edition)](http://www.amazon.com/Bayesian-Analysis-Chapman-Statistical-Science/dp/1439840954/) by Andrew Gelman, John Carlin, Hal Stern, David Dunson, Aki Vehtari, and Donald Rubin.:
    + Section 5.4: Estimating exchangeable parameters for a normal model
    + Section 5.5: Example: parallel experiments in eight schools
    + Section 5.7: Weakly informative priors for hierarchical variance parameters
    + Section 14.1: Conditional modeling
    + Section 14.2: Bayesian analysis of the classical regression model
    + Section 14.4: Goals of regression analysis
    + Section 14.5: Assembling the matrix of explanatory variables
    
    
