---
title: "Homework 2"
date: "Due: 11:59pm, Friday, February 19"
output: 
  html_document: 
    css: hw.css
    theme: yeti
    toc: true
    fig_caption: false
    toc_float:
      collapsed: false
      smooth_scroll: true
---

## Instructions

Please make sure your final output file is a pdf document. You can submit handwritten solutions for non-programming exercises or type them using R Markdown, LaTeX or any other word processor. All programming exercises must be done in R, typed up clearly and with all code attached. Submissions should be made on gradescope: go to Assignments $\rightarrow$ Homework 2.

## Questions

1. Let $$y_1,\ldots,y_n \overset{iid}{\sim} \textrm{Ga}(a,b)$$ where _a_ is known (so we only wish to infer _b_).
    + <font color="green">**Part (a):**</font> Find the conjugate family of priors for _b_.  
    <font color="blue">**(2 points)**</font>
    + <font color="green">**Part (b):**</font> Find the corresponding posterior given the prior you identified in the previous part.  
    <font color="blue">**(1 point)**</font>
    + <font color="green">**Part (c):**</font> Give an interpretation of the prior parameters as things like "prior mean", "prior variance", "prior sample size", etc.  
    <font color="blue">**(1 point)**</font>

2. Hoff 3.3
    + <font color="blue">**Part (a): 1 point**</font>
    + <font color="blue">**Part (b): 1 point**</font>
    + <font color="blue">**Part (c): 1 point**</font>

<!-- 4. Hoff 4.1 -->

<!-- 3. Hoff 4.3 -->

3. Hoff 4.8
    + <font color="blue">**Part (a): 2 points**</font>
    + <font color="blue">**Part (b): 2 points**</font>
    + <font color="blue">**Part (c): 2 points**</font>
    + <font color="blue">**Part (d): 2 points**</font>

    <font color="red">*You can find the data mentioned in the question here: http://www2.stat.duke.edu/~pdh10/FCBS/Exercises/. Clearly, you don't need to download and load the data, you can just enter it manually in R.* </font>
    
4. <font color="green">**How many samples is enough?**</font> Recall the birth rates example from the slides.  
    + <font color="green">**Part (a):**</font> Sample from the posterior distribution for women who are college educated using $m$ = 10, 100, and 1000 Monte Carlo samples. For each $m$, make a plot of the random draws and on the same plot, mark the points corresponding to the posterior mean and the 95% equal-tailed credible interval (quantile-based). How do those compare to the true posterior mean and 95% quantile-based CI?  
    <font color="blue">**(2 points)**</font>
    
    +  <font color="green">**Part (b):**</font> In addition, calculate the posterior probability that $\theta_2 < 1.5$ in each case.  
    <font color="blue">**(1.5 points)**</font>
    
    + <font color="green">**Part (c):**</font> How large should $m$ be if $95\%$ of the time we want the difference between the Monte Carlo estimate of the posterior mean and the true posterior mean (which we know in this case) to be $\leq 0.001$?  
    <font color="blue">**(1.5 points)**</font>


## Grading

20 points.
  