---
title: "Homework 3"
date: "Due: 11:59pm, Monday, July 20"
output: 
  html_document: 
    css: hw.css
    theme: yeti
    toc: true
    fig_caption: false
    toc_float:
      collapsed: false
      smooth_scroll: true
---

## Instructions

Please make sure your final output file is a pdf document. You can submit handwritten solutions for non-programming exercises or type them using R Markdown, LaTeX or any other word processor. All programming exercises must be done in R, typed up clearly and with all code attached. Submissions should be made on gradescope: go to Assignments $\rightarrow$ Homework 3 (360) for students in STA 360 and Homework 3 (602) for students in STA 602.

## Questions

1. Hoff problem 6.1
    + <font color="blue">**Part (a): Students in STA 360: 1 point; Students in STA 602: 1 point**</font>
    + <font color="blue">**Part (b): Students in STA 360: 2 points; Students in STA 602: 1.5 points**</font>
    + <font color="blue">**Part (c): Students in STA 360: 2 points; Students in STA 602: 1.5 points**</font>
    + <font color="blue">**Part (d): Students in STA 360: 3 points; Students in STA 602: 2 points**</font>

2. Suppose we have count data $y_i$ with $(i = 1,\ldots, n)$, where $x_i = 0$ for control subjects and $x_i = 1$ for treated subjects. Consider the following model for the data: $$y_i \sim \textrm{Poisson}(\lambda \gamma^{x_i}),$$ where $\lambda = \mathbb{E}[y_i | x_i = 0]$ and $\gamma$ is a multiplicative change in the mean in the treated group. Choose gamma priors for the parameters $\lambda$ and $\gamma$, $$\lambda \sim \textrm{Ga}(1,1),\ \ \ \gamma \sim \textrm{Ga}(1,1).$$
    + <font color="green">**Part (a):**</font>  Is the joint posterior for $\lambda$ and $\gamma$, that is, $\pi(\lambda,\gamma | X, Y)$, conjugate? Why or why not?  
    <font color="blue">**(Students in STA 360: 4 points; Students in STA 602: 3 points)**</font>
    + <font color="green">**Part (b):**</font>  Derive the full conditional distributions for $\lambda$ and $\gamma$.  
    <font color="blue">**(3 points for all students)**</font>
    + <font color="green">**Part (c):**</font>  Simulate data in which n = 100, with 50 in each group, where $\lambda = \gamma = 1$, and generate samples from the posterior distribution for these data.  
    <font color="blue">**(2 points for all students)**</font>
    + <font color="green">**Part (d):**</font>  Use your code to (i) estimate the posterior mean and a 95% credible interval for $\textrm{log}(\lambda)$; and (ii) estimate the predictive distribution for subjects having $x_i = 0$ and $x_i = 1$. Are these predictive distributions different?  
    <font color="blue">**(2 points for all students)**</font>
    + <font color="green">**Part (e):**</font>  Run convergence diagnostics -- is your chain mixing well? What is the effective sample size? Does the mixing differ for $\lambda$ and $\gamma$?  
    <font color="blue">**(1 point for all students)**</font>
    
3. <font color="green">**Rejection sampling.**</font>  
<font color="blue">**(Not graded for students in STA 360; you can attempt for practice but you don't need to submit. Graded for students in STA 602)**</font>  
Recall from class that the idea of rejection sampling is to create an importance/proposal/envelope function which is greater than or equal to the distribution we wish to sample from at all points, and which we can sample from easily. Suppose we end up with the following form for our posterior: $$f(\theta) \propto sin^2(\pi \theta), \ \ \ \theta \in [0,1],$$ where $\pi = 3.141593$.
This density looks like:
```{r fig.height=5.5, echo=F}
curve(sin(x*pi)^2,col="red3",
      xlab=expression(theta),ylab=expression(paste("sin(",pi,"",theta,")"^2)))
```
    + <font color="green">**Part (a):**</font> Implement a rejection sampler in R to sample from this density using a Unif(0,1) density as your proposal function, since it is greater than or equal to the given density (up to proportionality) at all points and is easy to sample from. Provide a plot of your sampled values.  
    <font color="blue">**(1 point for all students)**</font>
    + <font color="green">**Part (b):**</font> Propose a different envelope function and implement a rejection sampler for it in R. How does the efficiency of your envelope function compare to the uniform envelope function? Provide plots (histograms or density estimates) of the samples from the two approaches.  
    <font color="blue">**(2 points for all students)**</font>

## Grading

20 points.
  